services:
  redisDB:
    container_name: redisDB
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - '6379:6379'

  postgresDB:
    container_name: postgresDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:16.0-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - '5433:5432'

volumes:
  postgres-data:
