services:
  next_development:
    container_name: next_development
    image: luuppi.azurecr.io/next-dev:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_HOST=redis_next_development
    ports:
      - '127.0.0.1:3003:3000'
    depends_on:
      - redis_next_development
    networks:
      - weba-network

  redis_next_development:
    container_name: redis_next_development
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:6382:6379'
    networks:
      - weba-network

  pg_next_development:
    container_name: pg_next_development
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:16.0-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data/
    ports:
      - '127.0.0.1:5434:5432'
    networks:
      - weba-network

volumes:
  postgres-data-dev:

#
# External network handled by luuppi-proxy
# https://github.com/luuppiry/luuppi-proxy
#
networks:
  weba-network:
    external: true
